# https://www.playframework.com/documentation/latest/Configuration

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = [
    "http://localhost:3000",
    "https://drp-07.vercel.app"
  ]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Authorization"]
}

play.modules.enabled += "Module"

play.filters.hosts.allowed = ["."]